tree = Node('(object)', [
    Node('"states_daily" (array)', [
        Node('(object)', [
            Node('"date" (string)'),
            Node('"status" (string)'),
            Node('"an" (string)'),
            Node('"ap" (string)'),
            Node('"ar" (string)'),
            Node('"as" (string)'),
            Node('"br" (string)'),
            Node('"ch" (string)'),
            Node('"ct" (string)'),
            Node('"dd" (string)'),
            Node('"dl" (string)'),
            Node('"dn" (string)'),
            Node('"ga" (string)'),
            Node('"gj" (string)'),
            Node('"hp" (string)'),
            Node('"hr" (string)'),
            Node('"jh" (string)'),
            Node('"jk" (string)'),
            Node('"ka" (string)'),
            Node('"kl" (string)'),
            Node('"la" (string)'),
            Node('"ld" (string)'),
            Node('"mh" (string)'),
            Node('"ml" (string)'),
            Node('"mn" (string)'),
            Node('"mp" (string)'),
            Node('"mz" (string)'),
            Node('"nl" (string)'),
            Node('"or" (string)'),
            Node('"pb" (string)'),
            Node('"py" (string)'),
            Node('"rj" (string)'),
            Node('"sk" (string)'),
            Node('"tg" (string)'),
            Node('"tn" (string)'),
            Node('"tr" (string)'),
            Node('"tt" (string)'),
            Node('"up" (string)'),
            Node('"ut" (string)'),
            Node('"wb" (string)')
        ])
    ])
])
